Enhancements to support chat
Fliplet/fliplet-widget-data-directory pull request #26
Opened 2017-02-24 19:45 UTC by hcarneiro

2017-02-27 09:15 UTC, squallstar approved these changes

2017-03-01 14:39 UTC, tonytlwu requested changes

2017-03-01 14:39 UTC, tonytlwu commented on interface.html
> +                  <p>In what screen is your Chat?</p>
*Which screen is the Chat screen?*

2017-03-01 14:39 UTC, tonytlwu commented on interface.html
> +            <p>Selecting "Yes" will place a button in the detail view, that users can tap on to start a conversation.</p>
*Selecting "Yes" will place a **Send message** button in the user profile. Tapping on the button will start a conversation.*

2017-03-01 15:11 UTC, tonytlwu approved these changes

2017-03-01 15:14 UTC, merged